### PR TITLE
[Hotfix] Fix wheel by reverting __init__.py removal

### PR DESCRIPTION
**Pull request by gioelegott**
Fixes bug introduced in https://github.com/huawei-csl/pto-kernels/commit/60f46bf9ed544d1c1ad1b5b02f61181b5571f360

### CODE REVIEW

**Comment by zouzias** [comment]
Fixes 

```
ImportError while importing test module '/builds/zrc-von-neumann-lab/skyline-software/pto-kernels-mirror/tests/test_tri_inv_trick.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/python3.11.14/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_tri_inv_trick.py:10: in <module>
    from pto_kernels import pto_tri_inv_trick
E   ImportError: cannot import name 'pto_tri_inv_trick' from 'pto_kernels' (unknown location)
```

Merging.
